# Homebrew Formula for Vokt
# To install: brew install maneeshchaturvedi/vokt/vokt
#
# NOTE: This file is auto-generated by the vokt2.0 CI pipeline.
# The template lives in .github/workflows/release.yml (update-formula job).
# Manual edits here will be overwritten on the next release.

class Vokt < Formula
  desc "Behavioral code analysis — call graphs, risk scores, blast radius"
  homepage "https://github.com/maneeshchaturvedi/homebrew-vokt"
  version "2.0.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maneeshchaturvedi/homebrew-vokt/releases/download/v2.0.40/vokt-darwin-arm64"
      sha256 "efd1bf5adb449af277476ce4b9ff2a258bb91d18cf998391e82685b7bd67560e"

      resource "go-toolchain" do
        url "https://go.dev/dl/go1.25.darwin-arm64.tar.gz"
        sha256 "PLACEHOLDER_UNTIL_NEXT_CI_RUN"
      end
    else
      url "https://github.com/maneeshchaturvedi/homebrew-vokt/releases/download/v2.0.40/vokt-darwin-amd64"
      sha256 "acdd8d0f835956b54080151645d04f79510c289d375bfb1d248e51f12ec97806"

      resource "go-toolchain" do
        url "https://go.dev/dl/go1.25.darwin-amd64.tar.gz"
        sha256 "PLACEHOLDER_UNTIL_NEXT_CI_RUN"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/maneeshchaturvedi/homebrew-vokt/releases/download/v2.0.40/vokt-linux-arm64"
      sha256 "4b55473060669bc092256c868a4f8827dc35b580688fdd47b18b502c89379c54"

      resource "go-toolchain" do
        url "https://go.dev/dl/go1.25.linux-arm64.tar.gz"
        sha256 "PLACEHOLDER_UNTIL_NEXT_CI_RUN"
      end
    else
      url "https://github.com/maneeshchaturvedi/homebrew-vokt/releases/download/v2.0.40/vokt-linux-amd64"
      sha256 "0d9713e29a211a582e314cf9e85ed1af728832ff13ee35fcdc6c4569eb3e05d6"

      resource "go-toolchain" do
        url "https://go.dev/dl/go1.25.linux-amd64.tar.gz"
        sha256 "PLACEHOLDER_UNTIL_NEXT_CI_RUN"
      end
    end
  end

  # Java engine (platform-independent) for Java/JVM analysis
  resource "java-engine" do
    url "https://github.com/maneeshchaturvedi/homebrew-vokt/releases/download/v2.0.40/vokt-java-engine.jar"
  end

  # Tai-e runtime (LGPL, kept separate) — tarball of JARs
  resource "tai-e-deps" do
    url "https://github.com/maneeshchaturvedi/homebrew-vokt/releases/download/v2.0.40/tai-e-deps.tar.gz"
  end

  def install
    bin.install "vokt-darwin-arm64" => "vokt" if Hardware::CPU.arm? && OS.mac?
    bin.install "vokt-darwin-amd64" => "vokt" if Hardware::CPU.intel? && OS.mac?
    bin.install "vokt-linux-arm64" => "vokt" if Hardware::CPU.arm? && OS.linux?
    bin.install "vokt-linux-amd64" => "vokt" if Hardware::CPU.intel? && OS.linux?

    # Place Java engine JAR next to the binary
    resource("java-engine").stage { bin.install "vokt-java-engine.jar" }

    # Extract Tai-e runtime JARs into tai-e/ directory next to the binary
    (bin/"tai-e").mkpath
    resource("tai-e-deps").stage do
      (bin/"tai-e").install Dir["*.jar"]
    end

    # Bundle Go toolchain at lib/vokt/go/ — vokt auto-detects it via
    # ../lib/vokt/go/ relative to the binary. Ensures analysis works
    # regardless of whether Go is installed on the user's system.
    resource("go-toolchain").stage do
      (lib/"vokt").install "go"
    end
  end

  def caveats
    <<~EOS
      vokt bundles its own Go toolchain — you do not need Go installed to
      analyze Go projects. If a project requires a newer Go version, vokt
      will auto-download it on first use (via GOTOOLCHAIN=auto).

      Java analysis requires Java 17+. Set JAVA_HOME if java is not in PATH.
    EOS
  end

  test do
    assert_match "vokt", shell_output("#{bin}/vokt --version")
    assert_predicate lib/"vokt/go/bin/go", :executable?
  end
end
